branch-defaults:
  master:
    environment: vol-match-widget
    group_suffix: null
global:
  application_name: volunteer-match-widget
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
